# Generated by Django 5.0.6 on 2024-05-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_address', models.CharField(max_length=100)),
                ('perm_address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('food_preference', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('user_type', models.CharField(choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family')], max_length=10)),
                ('user_type_2', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Others', 'Others')], max_length=10)),
                ('interests', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
