# Generated by Django 5.0.6 on 2024-05-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_listed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lives_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
